algoritmo "numeros_multiplicados"
          var
             n1: real,
             n2: real,
             q: real,
             c: real
          inicio
          escreval("Digite o primeiro número: ")
          leia(n1)
          escreval("digite o segundo número: ")
          leia(n2)
          q := n1^2
          c := n2^3
          escreva("O quadrado do primeiro é: ",q," e o cubo do segundo é: ", c)
fimalgoritmo
